<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('products')->insert([
            [
                'name' => 'iPhone 12 64GB - ブラック - Simフリー',
                'price' => 50000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'black',
                'capacity' => 64,
                'image1' => 17,
                'image2' => 18,
                'image3' => 19,
                'image4' => 20,
            ],
            [
                'name' => 'iPhone 12 128GB - ブラック - Simフリー',
                'price' => 55000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'black',
                'capacity' => 128,
                'image1' => 17,
                'image2' => 18,
                'image3' => 19,
                'image4' => 20,
            ],
            [
                'name' => 'iPhone 12 256GB - ブラック - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'black',
                'capacity' => 256,
                'image1' => 17,
                'image2' => 18,
                'image3' => 19,
                'image4' => 20,
            ],

            [
                'name' => 'iPhone 12 64GB - ブルー - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'blue',
                'capacity' => 64,
                'image1' => 1,
                'image2' => 2,
                'image3' => 3,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 128GB - ブルー - Simフリー',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'blue',
                'capacity' => 128,
                'image1' => 1,
                'image2' => 2,
                'image3' => 3,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 256GB - ブルー - Simフリー',
                'price' => 65000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'blue',
                'capacity' => 256,
                'image1' => 1,
                'image2' => 2,
                'image3' => 3,
                'image4' => null,

            ],            
            [
                'name' => 'iPhone 12 64GB - (Product)Red - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'red',
                'capacity' => 64,
                'image1' => 8,
                'image2' => 9,
                'image3' => 10,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 128GB - (Product)Red - Simフリー',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'red',
                'capacity' => 128,
                'image1' => 8,
                'image2' => 9,
                'image3' => 10,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 256GB - (Product)Red - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'red',
                'capacity' => 256,
                'image1' => 8,
                'image2' => 9,
                'image3' => 10,
                'image4' => null,

            ],            
            [
                'name' => 'iPhone 12 64GB - パープル - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'purple',
                'capacity' => 64,
                'image1' => 4,
                'image2' => 5,
                'image3' => 6,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 128GB - パープル - Simフリー',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'purple',
                'capacity' => 128,
                'image1' => 4,
                'image2' => 5,
                'image3' => 6,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 256GB - パープル - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'purple',
                'capacity' => 256,
                'image1' => 4,
                'image2' => 5,
                'image3' => 6,
                'image4' => null,

            ], 
            [
                'name' => 'iPhone 12 64GB - グリーン - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'rightGreen',
                'capacity' => 64,
                'image1' => 14,
                'image2' => 15,
                'image3' => 16,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 128GB - グリーン - Simフリー',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'rightGreen',
                'capacity' => 128,
                'image1' => 14,
                'image2' => 15,
                'image3' => 16,
                'image4' => null,

            ],
            [
                'name' => 'iPhone 12 256GB - グリーン - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'rightGreen',
                'capacity' => 256,
                'image1' => 14,
                'image2' => 15,
                'image3' => 16,
                'image4' => null,

            ], 
            [
                'name' => 'iPhone 12 64GB - ホワイト  - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'white',
                'capacity' => 64,
                'image1' => 11,
                'image2' => 12,
                'image3' => 13,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 12 128GB - ホワイト  - Simフリー',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'white',
                'capacity' => 128,
                'image1' => 11,
                'image2' => 12,
                'image3' => 13,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 12 256GB - ホワイト  - Simフリー',
                'price' => 58000,
                'is_selling' => 1,
                'secondary_category_id' => 1,
                'color' => 'white',
                'capacity' => 256,
                'image1' => 11,
                'image2' => 12,
                'image3' => 13,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 128GB - ミッドナイト - Simフリー
                ',
                'price' => 85000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'black',
                'capacity' => 128,
                'image1' => 47,
                'image2' => 48,
                'image3' => 49,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 256GB - ミッドナイト - Simフリー',
                'price' => 95000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'black',
                'capacity' => 256,
                'image1' => 47,
                'image2' => 48,
                'image3' => 49,
                'image4' => null,
            ],            
            [
                'name' => 'iPhone 13 512GB - ミッドナイト - Simフリー',
                'price' => 123000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'black',
                'capacity' => 512,
                'image1' => 47,
                'image2' => 48,
                'image3' => 49,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 128GB - グリーン  - Simフリー',
                'price' => 85000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'green',
                'capacity' => 128,
                'image1' => 32,
                'image2' => 33,
                'image3' => 34,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 256GB - グリーン  - Simフリー',
                'price' => 95000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'green',
                'capacity' => 256,
                'image1' => 32,
                'image2' => 33,
                'image3' => 34,
                'image4' => null,
            ],            
            [
                'name' => 'iPhone 13 512GB - グリーン  - Simフリー',
                'price' => 123000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'green',
                'capacity' => 512,
                'image1' => 32,
                'image2' => 33,
                'image3' => 34,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 128GB - Red - Simフリー',
                'price' => 85000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'red',
                'capacity' => 128,
                'image1' => 37,
                'image2' => 35,
                'image3' => 36,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 256GB - Red - Simフリー',
                'price' => 95000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'red',
                'capacity' => 256,
                'image1' => 37,
                'image2' => 35,
                'image3' => 36,
                'image4' => null,
            ],            
            [
                'name' => 'iPhone 13 512GB - Red - Simフリー',
                'price' => 123000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'red',
                'capacity' => 512,
                'image1' => 37,
                'image2' => 35,
                'image3' => 36,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 128GB - ブルー - Simフリー',
                'price' => 85000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'blue',
                'capacity' => 128,
                'image1' => 38,
                'image2' => 39,
                'image3' => 40,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 256GB - ブルー - Simフリー',
                'price' => 95000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'blue',
                'capacity' => 256,
                'image1' => 38,
                'image2' => 39,
                'image3' => 40,
                'image4' => null,
            ],            
            [
                'name' => 'iPhone 13 512GB - ブルー - Simフリー',
                'price' => 123000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'blue',
                'capacity' => 512,
                'image1' => 38,
                'image2' => 39,
                'image3' => 40,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 128GB - ピンク - Simフリー',
                'price' => 85000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'pink',
                'capacity' => 128,
                'image1' => 41,
                'image2' => 42,
                'image3' => 43,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 256GB - ピンク - Simフリー',
                'price' => 95000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'pink',
                'capacity' => 256,
                'image1' => 41,
                'image2' => 42,
                'image3' => 43,
                'image4' => null,
            ],            
            [
                'name' => 'iPhone 13 512GB - ピンク - Simフリー',
                'price' => 123000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'pink',
                'capacity' => 512,
                'image1' => 41,
                'image2' => 42,
                'image3' => 43,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 128GB - スターライト - Simフリー',
                'price' => 85000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'white',
                'capacity' => 128,
                'image1' => 44,
                'image2' => 45,
                'image3' => 46,
                'image4' => null,
            ],
            [
                'name' => 'iPhone 13 256GB - スターライト - Simフリー',
                'price' => 95000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'white',
                'capacity' => 256,
                'image1' => 44,
                'image2' => 45,
                'image3' => 46,
                'image4' => null,
            ],            
            [
                'name' => 'iPhone 13 512GB - スターライト - Simフリー',
                'price' => 123000,
                'is_selling' => 1,
                'secondary_category_id' => 2,
                'color' => 'white',
                'capacity' => 512,
                'image1' => 58,
                'image2' => 59,
                'image3' => 60,
                'image4' => 61,
            ],
            [
                'name' => 'iPhone 14 128GB - ブルー - Simフリー',
                'price' => 97000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'blue',
                'capacity' => 128,
                'image1' => 58,
                'image2' => 59,
                'image3' => 60,
                'image4' => 61,
            ],            
            [
                'name' => 'iPhone 14 256GB - ブルー - Simフリー',
                'price' => 130000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'blue',
                'capacity' => 256,
                'image1' => 58,
                'image2' => 59,
                'image3' => 60,
                'image4' => 61,
            ],
            [
                'name' => 'iPhone 14 128GB - イエロー - Simフリー',
                'price' => 97000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'yellow',
                'capacity' => 128,
                'image1' => 54,
                'image2' => 55,
                'image3' => 56,
                'image4' => 57,
            ],            
            [
                'name' => 'iPhone 14 256GB - イエロー - Simフリー',
                'price' => 130000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'yellow',
                'capacity' => 256,
                'image1' => 54,
                'image2' => 55,
                'image3' => 56,
                'image4' => 57,
            ],
            [
                'name' => 'iPhone 14 128GB - ミッドナイト - Simフリー',
                'price' => 97000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'black',
                'capacity' => 128,
                'image1' => 110,
                'image2' => 111,
                'image3' => 112,
                'image4' => 113,
            ],            
            [
                'name' => 'iPhone 14 256GB - ミッドナイト - Simフリー',
                'price' => 130000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'black',
                'capacity' => 256,
                'image1' => 110,
                'image2' => 111,
                'image3' => 112,
                'image4' => 113,
            ],
            [
                'name' => 'iPhone 14 128GB - Red - Simフリー',
                'price' => 97000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'red',
                'capacity' => 128,
                'image1' => 51,
                'image2' => 52,
                'image3' => 53,
                'image4' => 50,
            ],            
            [
                'name' => 'iPhone 14 256GB - Red - Simフリー',
                'price' => 120000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'red',
                'capacity' => 256,
                'image1' => 51,
                'image2' => 52,
                'image3' => 53,
                'image4' => 50,
            ],
            [
                'name' => 'iPhone 14 128GB - パープル - Simフリー',
                'price' => 97000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'purple',
                'capacity' => 128,
                'image1' => 62,
                'image2' => 63,
                'image3' => 64,
                'image4' => 65,
            ],            
            [
                'name' => 'iPhone 14 256GB - パープル - Simフリー',
                'price' => 120000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'purple',
                'capacity' => 256,
                'image1' => 62,
                'image2' => 63,
                'image3' => 64,
                'image4' => 65,
            ],
            [
                'name' => 'iPhone 14 128GB - スターライト - Simフリー',
                'price' => 97000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'white',
                'capacity' => 128,
                'image1' => 66,
                'image2' => 69,
                'image3' => 68,
                'image4' => 67,
            ],            
            [
                'name' => 'iPhone 14 256GB - スターライト - Simフリー',
                'price' => 120000,
                'is_selling' => 1,
                'secondary_category_id' => 3,
                'color' => 'white',
                'capacity' => 256,
                'image1' => 66,
                'image2' => 69,
                'image3' => 68,
                'image4' => 67,
            ],
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 64GB - スペースグレイ',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 4,
                'color' => 'gray',
                'capacity' => 64,
                'image1' => 70,
                'image2' => 71,
                'image3' => 72,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - スペースグレイ',
                'price' => 90000,
                'is_selling' => 1,
                'secondary_category_id' => 4,
                'color' => 'gray',
                'capacity' => 256,
                'image1' => 70,
                'image2' => 71,
                'image3' => 72,
                'image4' => null,
            ],
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 64GB - パープル',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 4,
                'color' => 'purple',
                'capacity' => 64,
                'image1' => 75,
                'image2' => 76,
                'image3' => 72,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - パープル',
                'price' => 90000,
                'is_selling' => 1,
                'secondary_category_id' => 4,
                'color' => 'purple',
                'capacity' => 256,
                'image1' => 75,
                'image2' => 76,
                'image3' => 72,
                'image4' => null,
            ],
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 64GB - ピンク',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 4,
                'color' => 'pink',
                'capacity' => 64,
                'image1' => 77,
                'image2' => 78,
                'image3' => 72,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - ピンク',
                'price' => 90000,
                'is_selling' => 1,
                'secondary_category_id' => 4,
                'color' => 'pink',
                'capacity' => 256,
                'image1' => 77,
                'image2' => 78,
                'image3' => 72,
                'image4' => null,
            ],
            [
                'name' => 'iPad Air 10.9 インチ 第5世代- 64GB - スペースグレイ',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'gray',
                'capacity' => 64,
                'image1' => 82,
                'image2' => 83,
                'image3' => 84,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - スペースグレイ',
                'price' => 90000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'gray',
                'capacity' => 256,
                'image1' => 82,
                'image2' => 83,
                'image3' => 84,
                'image4' => null,
            ],
            [
                'name' => 'iPad Air 10.9 インチ 第5世代- 64GB - ブルー',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'blue',
                'capacity' => 64,
                'image1' => 88,
                'image2' => 89,
                'image3' => 90,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - ブルー',
                'price' => 90000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'blue',
                'capacity' => 256,
                'image1' => 88,
                'image2' => 89,
                'image3' => 90,
                'image4' => null,
            ],
            [
                'name' => 'iPad Air 10.9 インチ 第5世代- 64GB - パープル',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'purple',
                'capacity' => 64,
                'image1' => 91,
                'image2' => 92,
                'image3' => 93,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - パープル',
                'price' => 90000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'purple',
                'capacity' => 256,
                'image1' => 91,
                'image2' => 92,
                'image3' => 93,
                'image4' => null,
            ],
            [
                'name' => 'iPad Air 10.9 インチ 第5世代 - 64 GB - スターライト',
                'price' => 62000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'gold',
                'capacity' => 64,
                'image1' => 79,
                'image2' => 80,
                'image3' => 81,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - スターライト',
                'price' => 90000,
                'is_selling' => 1,
                'secondary_category_id' => 5,
                'color' => 'gold',
                'capacity' => 256,
                'image1' => 79,
                'image2' => 80,
                'image3' => 81,
                'image4' => null,
            ],
            [
                'name' => 'iPad Pro 11 インチ 第3世代- 128GB - スペースグレイ',
                'price' => 88000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 128,
                'image1' => 94,
                'image2' => 95,
                'image3' => null,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 256GB - スペースグレイ',
                'price' => 94000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 256,
                'image1' => 94,
                'image2' => 95,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'iPad Pro 11 インチ 第3世代- 512GB - スペースグレイ',
                'price' => 88000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 512,
                'image1' => 94,
                'image2' => 95,
                'image3' => null,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代- 1000GB - スペースグレイ',
                'price' => 94000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 1000,
                'image1' => 94,
                'image2' => 95,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'iPad Pro 11 インチ 第3世代 - 128 GB - シルバー',
                'price' => 88000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 128,
                'image1' => 96,
                'image2' => 97,
                'image3' => null,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代 - 256 GB - シルバー',
                'price' => 94000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 256,
                'image1' => 96,
                'image2' => 97,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'iPad Pro 11 インチ 第3世代 - 512 GB - シルバー',
                'price' => 88000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 512,
                'image1' => 96,
                'image2' => 97,
                'image3' => null,
                'image4' => null,
            ],            
            [
                'name' => 'iPad mini 8.3 インチ 第6世代 - 1000 GB - シルバー',
                'price' => 94000,
                'is_selling' => 1,
                'secondary_category_id' => 6,
                'color' => 'gray',
                'capacity' => 1000,
                'image1' => 96,
                'image2' => 97,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'MacBook Air 13 インチ - 8GB RAM - SSD 256GB スペースグレイ',
                'price' => 130000,
                'is_selling' => 1,
                'secondary_category_id' => 7,
                'color' => 'gray',
                'capacity' => 256,
                'image1' => 98,
                'image2' => 99,
                'image3' => 100,
                'image4' => null,
            ],            
            [
                'name' => 'MacBook Air 13 インチ - 8GB RAM - SSD 512GB スペースグレイ',
                'price' => 150000,
                'is_selling' => 1,
                'secondary_category_id' => 7,
                'color' => 'gray',
                'capacity' => 512,
                'image1' => 98,
                'image2' => 99,
                'image3' => 100,
                'image4' => null,
            ],
            [
                'name' => 'MacBook Air 13 インチ - 8GB RAM - SSD 256GB ゴールド',
                'price' => 130000,
                'is_selling' => 1,
                'secondary_category_id' => 7,
                'color' => 'gold',
                'capacity' => 256,
                'image1' => 101,
                'image2' => 102,
                'image3' => 103,
                'image4' => null,
            ],            
            [
                'name' => 'MacBook Air 13 インチ - 8GB RAM - SSD 512GB ゴールド',
                'price' => 150000,
                'is_selling' => 1,
                'secondary_category_id' => 7,
                'color' => 'gold',
                'capacity' => 512,
                'image1' => 101,
                'image2' => 102,
                'image3' => 103,
                'image4' => null,
            ],
            [
                'name' => 'MacBook Pro 14 インチ- 16GB - SSD 512GB スペースグレイ',
                'price' => 130000,
                'is_selling' => 1,
                'secondary_category_id' => 8,
                'color' => 'gray',
                'capacity' => 512,
                'image1' => 104,
                'image2' => 105,
                'image3' => 106,
                'image4' => null,
            ],            
            [
                'name' => 'MacBook Pro 14 インチ- 16GB - SSD 1000GB スペースグレイ',
                'price' => 150000,
                'is_selling' => 1,
                'secondary_category_id' => 8,
                'color' => 'gray',
                'capacity' => 1000,
                'image1' => 104,
                'image2' => 105,
                'image3' => 106,
                'image4' => null,
            ],
            [
                'name' => 'MacBook Pro 14 インチ- 16GB RAM - SSD 512GB シルバー',
                'price' => 130000,
                'is_selling' => 1,
                'secondary_category_id' => 8,
                'color' => 'silver',
                'capacity' => 512,
                'image1' => 107,
                'image2' => 108,
                'image3' => 109,
                'image4' => null,
            ],            
            [
                'name' => 'MacBook Pro 14 インチ- 16GB RAM - SSD 1000GB シルバー',
                'price' => 150000,
                'is_selling' => 1,
                'secondary_category_id' => 8,
                'color' => 'silver',
                'capacity' => 1000,
                'image1' => 107,
                'image2' => 108,
                'image3' => 109,
                'image4' => null,
            ],
            [
                'name' => 'Apple Watch Series 7 41mm - アルミニウム ',
                'price' => 43800,
                'is_selling' => 1,
                'secondary_category_id' => 9,
                'color' => 'none',
                'capacity' => 0,
                'image1' => 27,
                'image2' => 28,
                'image3' => 29,
                'image4' => null,
            ],            
            [
                'name' => 'Apple Watch Series 7 45mm - アルミニウム',
                'price' => 53000,
                'is_selling' => 1,
                'secondary_category_id' => 9,
                'color' => 'none',
                'capacity' => 0,
                'image1' => 27,
                'image2' => 28,
                'image3' => 29,
                'image4' => null,
            ],
            [
                'name' => 'Apple Watch Series 8 41mm - アルミニウム ',
                'price' => 53800,
                'is_selling' => 1,
                'secondary_category_id' => 10,
                'color' => 'none',
                'capacity' => 0,
                'image1' => 30,
                'image2' => 31,
                'image3' => null,
                'image4' => null,
            ],            
            [
                'name' => 'Apple Watch Series 8 45mm - アルミニウム',
                'price' => 60000,
                'is_selling' => 1,
                'secondary_category_id' => 10,
                'color' => 'none',
                'capacity' => 0,
                'image1' => 30,
                'image2' => 31,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Apple AirPods 第3世代 (2021) - MagSafe 充電ケース',
                'price' => 22000,
                'is_selling' => 1,
                'secondary_category_id' => 12,
                'color' => 'none',
                'capacity' => 0,
                'image1' => 21,
                'image2' => 22,
                'image3' => 23,
                'image4' => null,
            ],            
            [
                'name' => 'Apple AirPods Pro 第1世代 (2021) - MagSafe 充電ケース',
                'price' => 22000,
                'is_selling' => 1,
                'secondary_category_id' => 11,
                'color' => 'none',
                'capacity' => 0,
                'image1' => 24,
                'image2' => 25,
                'image3' => 26,
                'image4' => null,
            ],





        ]);
    }
}
